---
title: "Estimate cor — EM 2"
author: "Yuxin Zou"
date: 2018-8-2
output: 
  html_document:
    code_folding: hide
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

```{r}
library(mashr)
```

We use EM algorithm to update $\rho$.

B is the $n\times p$ true value matrix. $\mathbf{z}$ is a length n vector.

# E step

$$
P(\hat{B},B,\mathbf{z}|\rho, \pi) = \prod_{i=1}^{n} \prod_{p=0}^{P}\left[\pi_{p}N(\hat{b}_{i}; b_{i}, V)N(b_{i}; 0, \Sigma_{p})\right]^{\mathbb{I}(z_{i}=p)}
$$

$$
\mathbb{E}_{\mathbf{z},B|\hat{B}} \log P(\hat{B},B,\mathbf{z}|\rho, \pi) = \sum_{i=1}^{n} \sum_{p=0}^{P} \mathbb{E}_{b_{i}|\hat{b}_{i}}\left[ P(z_{i}=p|b_{i})\left( \log \pi_{p} + \log N(\hat{b}_{i}; b_{i}, V) + \log N(b_{i}; 0, \Sigma_{p}) \right) \right]
$$
$$
\gamma_{z_{i}}(p) = P(z_{i}=p|b_{i}) = \frac{\pi_{p}N(b_{i}; 0, \Sigma_{p})}{\sum_{p'=0}^{P}\pi_{p'}N(b_{i}; 0, \Sigma_{p'})}
$$

It is hard to compute the expectation.

# Session information

<!-- Insert the session information into the document -->
```{r session-info}
```

