---
title: "Estimate cor in `mashr`"
output:
  workflowr::wflow_html:
    toc: false
---

* [Estimate cor problem](EstimateCor.html)
    
* Using `optim` function to estimate cor: [Estimate cor optim](EstimateCorOptim.html)

* Using EM to estimate cor ($\rho$): 

    [Estimate cor EM optim](EstimateCorEM.html)
    
    [Estimate cor EM rho](EstimateCorEM2.html)

* Using EM to estimate cor ($V$): [Estimate cor EM V](EstimateCorMaxMV.html)

* The examples above are in $\mathcal{R}^{2}$. Here are more simulations to compare different methods for $R > 2$ : [Estimate cor in mash](EstimateCorMaxMash.html)

* Fewer iteration: [Estimate cor EM V fewer iteration](EstimateCorMaxMVIter.html) (niter = 3)

* Shorter Ulist: [Estimate cor EM V shorter Ulist](EstimateCorMaxMVUlist.html)

* Smaller samples: [Estimate cor EM V subset data](EstimateCorMaxMVSample.html)

* Problem: [mV problem](EstimateCorMaxMVProblem.html)

* MLE using reparametrization: [MLE compare](EstimateCorMLECompareDSC.html)

* Null Correlation Heterogeneity: [Cor Heterogeneity](EstimateCorHeter.html)

* Null Correlation Heterogeneity R = 50: [Cor Heterogeneity R = 50](EstimateCorHeterR50.html)

* Null Correlation Heterogeneity DSC: [Cor Heterogeneity DSC](DiffCorCompareDSC.html)

* Null Correlation Heterogeneity (with signals) DSC: [Cor Heterogeneity Signals DSC](DiffCorSignalCompareDSC.html)

