---
title: "Mash Missing Sample Size"
author: "Yuxin Zou"
date: 2018-3-1
output: 
  html_document:
    code_folding: hide
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r, echo=FALSE}
# TEMPORARY.
knitr::opts_chunk$set(eval = TRUE)
```

The weights from data R = 50, N = 400 are non-zero. Increasing the sample size to 800 and 3200, the weights shrink to 0. Decreasing the sampel size to 400 provides the correct weights as well.

# N = 400
```{r}
library(mashr)
set.seed(2018)
data = simple_sims(100, 50, err_sd = 0.1)

mash.data = mash_set_data(data$Bhat, data$Shat)
U.c = cov_canonical(mash.data)

mash.model = mash(mash.data, U.c)
barplot(get_estimated_pi(mash.model), las=2, cex.names = 0.7)
```

# Increase to N = 800
```{r}
set.seed(2018)
data = simple_sims(200, 50, err_sd = 0.1)

mash.data = mash_set_data(data$Bhat, data$Shat)
U.c = cov_canonical(mash.data)

mash.model = mash(mash.data, U.c)
barplot(get_estimated_pi(mash.model), las=2, cex.names = 0.7)
```

There are some shinkage for the small weights.

# Increase to N = 3200
```{r}
set.seed(2018)
data = simple_sims(800, 50, err_sd = 0.1)

mash.data = mash_set_data(data$Bhat, data$Shat)
U.c = cov_canonical(mash.data)

mash.model = mash(mash.data, U.c)
barplot(get_estimated_pi(mash.model), las=2, cex.names = 0.7)
```

# Decrease to N = 300
```{r}
set.seed(2018)
data = simple_sims(75, 50, err_sd = 0.1)

mash.data = mash_set_data(data$Bhat, data$Shat)
U.c = cov_canonical(mash.data)

mash.model = mash(mash.data, U.c)
barplot(get_estimated_pi(mash.model), las=2, cex.names = 0.7)
```

The weights learnd from N=300 model is correct.

# Session information
<!-- Insert the session information into the document -->
```{r session-info}
```
